version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: 
          name: Get dependencies
          command: go get ./...
      - run: 
          name: Build
          command: go build
  test:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: 
          name: Get dependencies
          command: go get ./...
      - run: 
          name: Prepare
          command: |
            go get -u github.com/jstemmer/go-junit-report;
            mkdir results;
      - run:
          name: Tests
          command: go test -v -race -coverprofile cover.out 2>&1 | tee /dev/tty | go-junit-report > results/results.xml
      - run: 
          name: Format coverage
          command: go tool cover -html=cover.out -o coverage.html
      - store_artifacts:
          path: coverage.html
      - store_test_results:
          path: results

workflows:
  version: 2
  build_and_test:
     jobs:
      - build
      - test:
          requires:
            - build