name: Go
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
      - name: Prepare similator
        run: |
          go install github.com/slytomcat/yandex-disk-simulator@latest 
          mv $(which yandex-disk-simulator) yandex-disk
      - name: Test
        run: |
          export PATH=$(pwd):$PATH
          go test -v --race -coverprofile cover.out ./...
      - name: Format coverage
        run: go tool cover -html=cover.out -o coverage.html
      - name: Upload coverage to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage_artifacts
          path: coverage.html
